# Generated by Django 5.2.6 on 2025-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В обработке'), ('closed', 'Закрыта'), ('rejected', 'Отклонена'), ('waiting', 'Ожидает')], default='in_progress', max_length=20, verbose_name='Статус заявки')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель товара')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('warranty_status', models.CharField(choices=[('warranty', 'На гарантии'), ('expired', 'Гарантия истекла'), ('unknown', 'Неизвестно')], max_length=20, verbose_name='Статус гарантии')),
                ('problem_description', models.TextField(verbose_name='Описание неисправности')),
                ('customer_name', models.CharField(max_length=150, verbose_name='ФИО покупателя')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('dealer_name', models.CharField(max_length=150, verbose_name='Название дилера')),
                ('dealer_city', models.CharField(max_length=100, verbose_name='Город')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Дополнительно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
        ),
    ]
