# Generated by Django 5.2.6 on 2025-10-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_track_app', '0010_alter_repairrequest_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='return_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина возврата'),
        ),
        migrations.AddField(
            model_name='package',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлен производителю'), ('accepted', 'Принят производителем'), ('returned', 'Возвращен дилеру'), ('processing', 'В обработке у производителя')], default='sent', max_length=20, verbose_name='Статус пакета'),
        ),
    ]
