# Generated by Django 5.2.6 on 2025-10-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_track_app', '0011_package_return_reason_package_returned_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название модели')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('series', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия')),
                ('category', models.CharField(blank=True, choices=[('subwoofer', 'Сабвуфер'), ('amplifier', 'Усилитель'), ('speaker', 'Динамик'), ('component', 'Компонентная акустика'), ('coaxial', 'Коаксиальная акустика'), ('midrange', 'Мидрейндж'), ('tweeter', 'Твитер'), ('accessory', 'Аксессуар')], max_length=50, null=True, verbose_name='Категория')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер')),
                ('power_rms', models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность RMS')),
                ('power_max', models.CharField(blank=True, max_length=50, null=True, verbose_name='Мощность MAX')),
                ('external_id', models.CharField(blank=True, help_text='ID из внешней системы', max_length=50, null=True, verbose_name='Внешний ID')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на товар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['brand', 'name'],
            },
        ),
    ]
