# Generated by Django 5.2.6 on 2025-10-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_track_app', '0012_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('subwoofer', 'Сабвуфер'), ('amplifier', 'Усилитель'), ('speaker', 'Динамик'), ('component', 'Компонентная акустика'), ('coaxial', 'Коаксиальная акустика'), ('midrange', 'Мидрейндж'), ('tweeter', 'Твитер'), ('accessory', 'Аксессуар')], default='subwoofer', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_requests', to='service_track_app.product', verbose_name='Товар'),
        ),
    ]
